
var customerAccounts = 
	 [
		{
			"customerId": 1045300,
			"nameOnAccount": "John",
			"accountName": "Credit Card",
			"accountNickname": "Rewards Card",
			"accountNumber": "1045301",
			"accountType": "Credit Card",
			"status": "active",
			"currency": "USD",
			"availableBalance": 8547.43,
			"currentBalance": null,
			"minimumBalance": null,
			"creditLimit": 10000,
			"statementDate": "04/20/2023",
			"activatedDate": "01-01-2010",
			"deactivatedDate": "",
			"lastUpdated": "01-08-2019",
			"image": "",
			"availableCredit": 1452.57,
			"unbilledAmount": 5698.17,
			"dueAmount": 7500,
			"dueDate": "05/25/2023",
			"cardNumber": "1234456778901234",
			"minimumPaymentDue": 300,
			"rewardPoints": 123,
			"expiryDate": "01-01-2025",
			"availableCash": 200,
			"personalBankerName": "",
			"maxTransactionLimit": null,
			"userID": "fa66596f0c9cb924",
			"cardType": "Primary",
			"cardNetwork": "Visa",
			"cardName": "Bank of America",
			"P2PLimit": null,
			"CardStatus": "frozen",
			"routingNumber": 122235821,
			"availableCashLimit": 1000,
			"principalBalance": null,
			"payoffAmount": null,
			"originalLoanAmount": null,
			"loanOriginationDate": "",
			"monthlyPayment": null,
			"propertyAddress": "",
			"lastDrawDate": "",
			"productName": "",
			"productCode": "CC01",
			"totalBalance": 13198.17,
			"postedBalance": null,
			"loanMaturityDate": "",
			"location": "161 River Marsh Dr, Ponte Vedra Beach, Florida, 32082",
			"email": "test13@gmail.com",
			"phone": 14085040880,
			"expDate": "0125",
			"maturityDate": "",
			"interestRate": null,
			"valueAtMaturity": null,
			"earlyWithdrawalPenalty": null,
			"internalTransferFromEnabled": true,
			"internalTransferToEnabled": true,
			"p2pEnabled": true,
			"paybillEnabled": true,
			"swiftCode": "",
			"branchName": "",
			"bankName": "",
			"openingBalance": null,
			"netWithdrawableBalance": null,
			"holdAmount": null,
			"unclearFundsAmount": null,
			"averageMonthlyBalance": null,
			"fdType": "",
			"totalTenure": "",
			"paidTenure": "",
			"remainingTenure": "",
			"debitAccountNumber": "",
			"lateFee": null,
			"bounceCharge": null,
			"totalCharges": null,
			"overDueAmount": null,
			"lastEmiPaidOn": "",
			"repaymentAccountNumber": null,
			"repaymentBankName": "",
			"cardChannelInfo": {
				"ATM": {
					"enable": false,
					"limit": 20000
				},
				"offline": {
					"enable": true,
					"limit": 20000
				},
				"international": {
					"enable": false,
					"limit": 100000
				},
				"online": {
					"enable": false,
					"limit": 20000
				},
				"contactless": {
					"enable": true,
					"limit": 20000
				}
			},
			"currentPeriodRewardPoints": null,
			"emiCount": null,
			"blockReason": "",
			"freezeType": "",
			"partialPaymentPaid": 1523,
			"iban": "",
			"holdingType": "",
			"openingDate": "",
			"cardDetails": [
				{
					"cardName": "Bank of America",
					"cardNumber": "1234456778901234",
					"cardStatus": "active",
					"cardImage": "",
					"cardType": "Primary",
					"expDate": "0125",
					"autopay": {},
					"cardChannelInfo": {
						"ATM": {
							"enable": false,
							"limit": 20000
						},
						"offline": {
							"enable": true,
							"limit": 20000
						},
						"international": {
							"enable": false,
							"limit": 100000
						},
						"online": {
							"enable": false,
							"limit": 20000
						},
						"contactless": {
							"enable": true,
							"limit": 20000
						}
					},
					"cardRestrictions": {},
					"rewardPoints": "123",
					"blockReason": "",
					"nameOnCard": "",
					"cardNetwork": "Visa",
					"displayCardStatus": "Active",
					"dueDate": "06/25/2021",
					"minimumPaymentDue": "300",
					"partialPaymentPaid": "1523"
				}
			],
			"isStatement": false,
			"isPrimaryMobileNumber": false,
			"isAlternateMobileNumber": false,
			"hasMissedEMI": false,
			"id": "2291318db18228a3",
			"label": "Credit Card - 1234",
			"nicknameLabel": "Rewards Card - 5301",
			"synonym": [
				"\"1045301\"",
				"\"5301\"",
				"\"rewards card\"",
				"\"1234\"",
				"\"Rewards Card - 5301\"",
				"\"Credit Card - 1234\"",
				"\"Rewards Card - 1234\"",
				"\"1234456778901234\"",
				"\"1234 4567 7890 1234\"",
				"\"Bank of America\"",
				"\"Credit Card\"",
				"\"~creditcardsynonyms\"",
				"\"bank of\"",
				"\"bank america\"",
				"\"of america\""
			]
		},
		{
			"customerId": 1045300,
			"nameOnAccount": "John",
			"accountName": "Savings Account",
			"accountNickname": "Vacation Fund",
			"accountNumber": "1043693",
			"accountType": "Savings Account",
			"status": "active",
			"currency": "USD",
			"availableBalance": 2256.93,
			"currentBalance": 20,
			"minimumBalance": 1500,
			"creditLimit": null,
			"statementDate": "",
			"activatedDate": "01-01-2011",
			"deactivatedDate": "",
			"lastUpdated": "01-07-2019",
			"image": "",
			"availableCredit": null,
			"unbilledAmount": null,
			"dueAmount": null,
			"dueDate": "",
			"cardNumber": null,
			"minimumPaymentDue": null,
			"rewardPoints": null,
			"expiryDate": "",
			"availableCash": null,
			"personalBankerName": "William Smith",
			"personalBankerContact": {
				"email": "William.Smith@bank.com",
				"mobileNumber": "(904) 236-2345"
			},
			"maxTransactionLimit": 400000,
			"userID": "fa66596f0c9cb924",
			"cardType": "",
			"cardNetwork": "Discover",
			"cardName": "Wells Fargo",
			"P2PLimit": 300,
			"CardStatus": "",
			"routingNumber": 122105159,
			"availableCashLimit": 500,
			"principalBalance": null,
			"payoffAmount": null,
			"originalLoanAmount": null,
			"loanOriginationDate": "",
			"monthlyPayment": null,
			"propertyAddress": "",
			"lastDrawDate": "",
			"productName": "\"Boost Savings\"",
			"productCode": "MS02",
			"totalBalance": null,
			"postedBalance": null,
			"loanMaturityDate": "",
			"location": "172 W Flagler Street, Miami, Florida, 33130",
			"email": "test12@gmail.com",
			"phone": 14085040880,
			"expDate": "",
			"maturityDate": "",
			"interestRate": null,
			"valueAtMaturity": null,
			"earlyWithdrawalPenalty": null,
			"internalTransferFromEnabled": true,
			"internalTransferToEnabled": true,
			"p2pEnabled": true,
			"paybillEnabled": true,
			"swiftCode": "",
			"branchName": "",
			"bankName": "",
			"openingBalance": null,
			"netWithdrawableBalance": null,
			"holdAmount": null,
			"unclearFundsAmount": null,
			"averageMonthlyBalance": null,
			"fdType": "",
			"totalTenure": "",
			"paidTenure": "",
			"remainingTenure": "",
			"debitAccountNumber": "",
			"lateFee": null,
			"bounceCharge": null,
			"totalCharges": null,
			"overDueAmount": null,
			"lastEmiPaidOn": "",
			"repaymentAccountNumber": null,
			"repaymentBankName": "",
			"currentPeriodRewardPoints": null,
			"emiCount": null,
			"blockReason": "",
			"freezeType": "",
			"partialPaymentPaid": null,
			"iban": "",
			"holdingType": "",
			"openingDate": "",
			"cardDetails": [
				{
					"cardName": "Wells Fargo",
					"cardNumber": "",
					"cardStatus": "active",
					"cardImage": "",
					"cardType": "primary",
					"expDate": "",
					"autopay": {},
					"cardChannelInfo": {},
					"cardRestrictions": {},
					"rewardPoints": "",
					"blockReason": "",
					"nameOnCard": "",
					"cardNetwork": "Discover",
					"displayCardStatus": "Active",
					"dueDate": "",
					"minimumPaymentDue": "",
					"partialPaymentPaid": ""
				}
			],
			"isStatement": false,
			"isPrimaryMobileNumber": false,
			"isAlternateMobileNumber": false,
			"hasMissedEMI": false,
			"id": "ae8fcadaaceaeaa1",
			"label": "Savings Account - 3693",
			"nicknameLabel": "Vacation Fund - 3693",
			"synonym": [
				"\"1043693\"",
				"\"3693\"",
				"\"vacation fund\"",
				"\"Boost Savings\"",
				"\"Debit Card\"",
				"\"Wells Fargo\"",
				"\"Vacation Fund - 3693\"",
				"\"Savings Account - 3693\"",
				"\"Savings Account\"",
				"\"~savingsaccountsynonyms\""
			]
		},
		{
			"CardStatus": "frozen",
			"P2PLimit": 7000,
			"accountName": "Checking Account",
			"accountNickname": "Joint",
			"accountNumber": "1042345",
			"accountType": "Checking Account",
			"activatedDate": "03-01-2010",
			"availableBalance": 6423.01,
			"availableCash": 1000,
			"availableCashLimit": 1000,
			"availableCredit": null,
			"averageMonthlyBalance": null,
			"bankName": "",
			"blockReason": "",
			"bounceCharge": null,
			"branchName": "",
			"cardChannelInfo": {
				"ATM": {
					"enable": false,
					"limit": 20000
				},
				"offline": {
					"enable": true,
					"limit": 20000
				},
				"international": {
					"enable": false,
					"limit": 100000
				},
				"online": {
					"enable": false,
					"limit": 20000
				},
				"contactless": {
					"enable": true,
					"limit": 20000
				}
			},
			"cardDetails": [
				{
					"cardName": "VISA Platinum",
					"cardNumber": "1234456778901690",
					"cardStatus": "frozen",
					"cardImage": "",
					"cardType": "Primary",
					"expDate": "0125",
					"autopay": {},
					"cardChannelInfo": {
						"ATM": {
							"enable": false,
							"limit": 20000
						},
						"offline": {
							"enable": true,
							"limit": 20000
						},
						"international": {
							"enable": false,
							"limit": 100000
						},
						"online": {
							"enable": false,
							"limit": 20000
						},
						"contactless": {
							"enable": true,
							"limit": 20000
						}
					},
					"cardRestrictions": {},
					"rewardPoints": "",
					"blockReason": "",
					"nameOnCard": "",
					"cardNetwork": "Discover",
					"displayCardStatus": "Temporary Lock",
					"dueDate": "",
					"minimumPaymentDue": "",
					"partialPaymentPaid": ""
				}
			],
			"cardName": "",
			"cardNetwork": "",
			"cardNumber": "1234456778901690",
			"cardType": "Primary",
			"chequeBookDetails": {
				"enabled": false
			},
			"creditLimit": null,
			"currency": "USD",
			"currentBalance": null,
			"currentPeriodRewardPoints": 5500,
			"customerId": 1045300,
			"deactivatedDate": "",
			"debitAccountNumber": "",
			"dueAmount": null,
			"dueDate": "",
			"earlyWithdrawalPenalty": null,
			"email": "test14@gmail.com",
			"emiCount": null,
			"expDate": "0125",
			"expiryDate": "01-01-2025",
			"fdType": "",
			"freezeType": "temporary",
			"hasMissedEMI": false,
			"holdAmount": null,
			"holdingType": "",
			"iban": "",
			"image": "",
			"interestRate": null,
			"internalTransferFromEnabled": true,
			"internalTransferToEnabled": true,
			"isAlternateMobileNumber": false,
			"isPrimaryMobileNumber": false,
			"isStatement": false,
			"lastDrawDate": "",
			"lastEmiPaidOn": "",
			"lastUpdated": "01-08-2019",
			"lateFee": null,
			"loanMaturityDate": "",
			"loanOriginationDate": "",
			"location": "1234 Main street, New York, 32819",
			"maturityDate": "",
			"maxTransactionLimit": 400000,
			"minimumBalance": 1300,
			"minimumPaymentDue": null,
			"monthlyPayment": null,
			"nameOnAccount": "John",
			"netWithdrawableBalance": null,
			"openingBalance": null,
			"openingDate": "",
			"originalLoanAmount": null,
			"overDueAmount": null,
			"p2pEnabled": true,
			"paidTenure": "",
			"partialPaymentPaid": null,
			"paybillEnabled": true,
			"payoffAmount": null,
			"personalBankerName": "",
			"phone": 14085040880,
			"postedBalance": null,
			"principalBalance": null,
			"productCode": "BC06",
			"productName": "\"Basic Checking\"",
			"propertyAddress": "",
			"remainingTenure": "",
			"repaymentAccountNumber": null,
			"repaymentBankName": "",
			"rewardPoints": null,
			"routingNumber": 121122676,
			"statementDate": "",
			"status": "active",
			"swiftCode": "",
			"totalBalance": null,
			"totalCharges": null,
			"totalTenure": "",
			"unbilledAmount": null,
			"unclearFundsAmount": null,
			"userID": "fa66596f0c9cb924",
			"valueAtMaturity": null,
			"id": "0a63b8fc4fef2986",
			"label": "Checking Account - 2345",
			"nicknameLabel": "Joint - 2345",
			"synonym": [
				"\"1042345\"",
				"\"2345\"",
				"\"joint\"",
				"\"Basic Checking\"",
				"\"Debit Card\"",
				"\"1234456778901690\"",
				"\"1234 4567 7890 1690\"",
				"\"1690\"",
				"\"Debit Card - 1690\"",
				"\"VISA Platinum\"",
				"\"VISA Platinum - 1690\"",
				"\"Primary - 1690\"",
				"\"Joint - 2345\"",
				"\"Checking Account - 2345\"",
				"\"Checking Account\"",
				"\"~checkingaccountsynonyms\""
			]
		},
		{
			"customerId": 1045300,
			"nameOnAccount": "John",
			"accountName": "Savings Account",
			"accountNickname": "Joint with Son",
			"accountNumber": "1042222",
			"accountType": "Savings Account",
			"status": "active",
			"currency": "USD",
			"availableBalance": 5649.65,
			"currentBalance": 20,
			"minimumBalance": 1500,
			"creditLimit": null,
			"statementDate": "",
			"activatedDate": "01-01-2011",
			"deactivatedDate": "",
			"lastUpdated": "01-07-2019",
			"image": "",
			"availableCredit": null,
			"unbilledAmount": null,
			"dueAmount": null,
			"dueDate": "",
			"cardNumber": null,
			"minimumPaymentDue": null,
			"rewardPoints": null,
			"expiryDate": "",
			"availableCash": null,
			"personalBankerName": "William Smith",
			"personalBankerContact": {
				"email": "William.Smith@bank.com",
				"mobileNumber": "(904) 236-2345"
			},
			"maxTransactionLimit": 400000,
			"userID": "fa66596f0c9cb924",
			"cardType": "",
			"cardNetwork": "Discover",
			"cardName": "Wells Fargo",
			"P2PLimit": 450,
			"CardStatus": "",
			"routingNumber": 122105155,
			"availableCashLimit": 1500,
			"principalBalance": null,
			"payoffAmount": null,
			"originalLoanAmount": null,
			"loanOriginationDate": "",
			"monthlyPayment": null,
			"propertyAddress": "",
			"lastDrawDate": "",
			"productName": "\"Basic Savings\"",
			"productCode": "BS03",
			"totalBalance": null,
			"postedBalance": null,
			"loanMaturityDate": "",
			"location": "1320 Park avenue, Orlando, Florida, 76656",
			"email": "testing11@gmail.com",
			"phone": 14085040880,
			"expDate": "",
			"maturityDate": "",
			"interestRate": null,
			"valueAtMaturity": null,
			"earlyWithdrawalPenalty": null,
			"internalTransferFromEnabled": true,
			"internalTransferToEnabled": true,
			"p2pEnabled": true,
			"paybillEnabled": true,
			"swiftCode": "",
			"branchName": "",
			"bankName": "",
			"openingBalance": null,
			"netWithdrawableBalance": null,
			"holdAmount": null,
			"unclearFundsAmount": null,
			"averageMonthlyBalance": null,
			"fdType": "",
			"totalTenure": "",
			"paidTenure": "",
			"remainingTenure": "",
			"debitAccountNumber": "",
			"lateFee": null,
			"bounceCharge": null,
			"totalCharges": null,
			"overDueAmount": null,
			"lastEmiPaidOn": "",
			"repaymentAccountNumber": null,
			"repaymentBankName": "",
			"currentPeriodRewardPoints": null,
			"emiCount": null,
			"blockReason": "",
			"freezeType": "",
			"partialPaymentPaid": null,
			"iban": "",
			"holdingType": "",
			"openingDate": "",
			"cardDetails": [
				{
					"cardName": "Wells Fargo",
					"cardNumber": "",
					"cardStatus": "active",
					"cardImage": "",
					"cardType": "primary",
					"expDate": "",
					"autopay": {},
					"cardChannelInfo": {},
					"cardRestrictions": {},
					"rewardPoints": "",
					"blockReason": "",
					"nameOnCard": "",
					"cardNetwork": "Discover",
					"displayCardStatus": "Active",
					"dueDate": "",
					"minimumPaymentDue": "",
					"partialPaymentPaid": ""
				}
			],
			"isStatement": false,
			"isPrimaryMobileNumber": false,
			"isAlternateMobileNumber": false,
			"hasMissedEMI": false,
			"id": "ba02da06c13b68fe",
			"label": "Savings Account - 2222",
			"nicknameLabel": "Joint with Son - 2222",
			"synonym": [
				"\"1042222\"",
				"\"2222\"",
				"\"joint with son\"",
				"\"Basic Savings\"",
				"\"Debit Card\"",
				"\"Wells Fargo\"",
				"\"Joint with Son - 2222\"",
				"\"Savings Account - 2222\"",
				"\"Savings Account\"",
				"\"~savingsaccountsynonyms\""
			]
		}
	];
customerAccounts= customerAccounts.filter(item=>["1042222","1045301"].includes(item.accountNumber));
console.log(customerAccounts.length);
